#!/usr/bin/env bash
# lock-fleets use new-cards, entry srv2-03: cold start c3 of srv2_35b_32k (d-srv2-35b); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: new-cards-srv2-c3-srv2_35b_32k.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" new-cards-srv2-c3-srv2_35b_32k.json srv2_35b_32k "$@"
