"""The `observed` block: captured comprehensively, compared by nothing (#286).

D7. The properties here are the ones a later reader has to be able to
trust without re-deriving them: every declared field is present, a null carries
a reason, nothing on the way in reaches disk unredacted, and — the one that is
not about content — **nothing reads this file**. That last one is a test rather
than a docstring because it is the property a future lane is most likely to
break by accident, by wiring a guard to a field that is comprehensive precisely
because nobody admitted it.
"""

from __future__ import annotations

import ast
import json
import subprocess
import sys
import types
from pathlib import Path
from typing import Any

import pytest

from tests._helpers import by_path

REPO = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="module")
def observed() -> Any:
    return by_path("bench_observed", REPO / "tools" / "bench" / "observed.py")


# The two documents, in the shape srv2 (ollama 0.32.5) returned them on
# 2026-08-18 for `qwen2.5-coder:1.5b`, cut down to the keys under test. The
# tokenizer arrays are the real lengths in miniature. Since D5 they are elided
# by NAME, not by length — `MAX_INLINE_ITEMS` is only the backstop for an array
# nobody named — so their sizes no longer straddle a threshold and are simply
# realistic. The size relation the earlier version of this comment described
# stopped being the rule the code applies.
TAGS: dict[str, Any] = {
    "models": [
        {
            "name": "qwen2.5-coder:1.5b",
            "model": "qwen2.5-coder:1.5b",
            "digest": "d7372fd828518a4d",
            "details": {
                "family": "qwen2",
                "parameter_size": "1.5B",
                "quantization_level": "Q4_K_M",
                "context_length": 32768,
            },
        }
    ]
}

SHOW: dict[str, Any] = {
    "details": {"family": "qwen2", "quantization_level": "Q4_K_M"},
    "template": "{{ .Prompt }}",
    "modelfile": (
        '# Modelfile generated by "ollama show"\n'
        "FROM /usr/share/ollama/.ollama/models/blobs/sha256-29d8c98fa6b0\n"
    ),
    "model_info": {
        "general.architecture": "qwen2",
        "qwen2.context_length": 32768,
        "tokenizer.ggml.tokens": [f"t{i}" for i in range(1000)],
        "tokenizer.ggml.pre": "qwen2",
    },
    "tensors": [{"name": "token_embd.weight", "type": "Q6_K", "shape": [1536, 151936]}],
    "capabilities": ["completion", "tools", "insert"],
}


def _endpoint(
    observed: Any,
    monkeypatch: pytest.MonkeyPatch,
    tags: Any,
    show: Any,
    *,
    ps: Any = None,
    models: Any = None,
    version: Any = None,
    server_info: Any = None,
    metrics: str | None = None,
) -> None:
    """A server, without one — routed by URL, through the module's own seams.

    Routed rather than answered flat because the engine is identified from
    *which* calls come back: a fake that returned the same document to
    ``/api/tags`` and ``/v1/models`` would make every arm look like ollama, and
    the dispatch this file exists to test would never run.
    """
    table = {
        "/api/tags": tags,
        "/api/ps": ps,
        "/api/version": version if tags is not None else None,
        "/v1/models": models,
        "/version": version if tags is None else None,
        "/server_info": server_info,
    }

    def get(url: str, *, timeout: float) -> Any:
        for path, answer in table.items():
            if url.endswith(path):
                return answer
        return None

    monkeypatch.setattr(observed.identity, "_get_json", get, raising=True)
    monkeypatch.setattr(
        observed.identity, "_post_json", lambda url, body, *, timeout: show
    )
    monkeypatch.setattr(
        observed, "_get_text", lambda url, *, timeout: metrics, raising=True
    )


# `/api/ps` for a RESIDENT model, in the shape both rigs returned on
# 2026-08-18. `context_length` here is 4096 — ollama's `num_ctx` default —
# against the 32768 trained window `/api/tags` and `/api/show` report.
PS: dict[str, Any] = {
    "models": [
        {
            "name": "qwen2.5-coder:1.5b",
            "model": "qwen2.5-coder:1.5b",
            "size_vram": 1166236712,
            "context_length": 4096,
            "details": {"quantization_level": "Q4_K_M"},
        }
    ]
}

# vLLM 0.26.0, measured on srv1 (1.5B-AWQ, --max-model-len 8192,
# --max-num-seqs 8) and srv2 (7B-AWQ, --max-model-len 16384, --max-num-seqs 16)
# on 2026-08-18. These are cut-down copies of what those servers returned.
VLLM_MODELS: dict[str, Any] = {
    "object": "list",
    "data": [
        {
            "id": "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ",
            "object": "model",
            "owned_by": "vllm",
            "root": "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ",
            "parent": None,
            "max_model_len": 8192,
        }
    ],
}

# `/server_info` exists ONLY under VLLM_SERVER_DEV_MODE=1, and `vllm_config` is
# a Python repr rather than a JSON object — 3,118 characters on srv1. This is
# the head of the real string, which is where all three settings sit.
VLLM_SERVER_INFO: dict[str, Any] = {
    "vllm_config": (
        "model='Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ', speculative_config=None, "
        "dtype=torch.float16, max_seq_len=8192, tensor_parallel_size=1, "
        "quantization=auto_awq, quantization_config=None, enforce_eager=True, "
        "kv_cache_dtype=auto, device_config=cuda, seed=0, "
        "served_model_name=Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ, "
        "enable_prefix_caching=True, enable_chunked_prefill=True"
    ),
    "vllm_env": {"VLLM_ALLOW_LONG_MAX_MODEL_LEN": False},
}

# srv1's real `cache_config_info` labels. `kv_cache_max_concurrency` is the
# value that LOOKS like the answer for `concurrency` and is not — see the test
# that pins the refutation.
VLLM_METRICS = (
    "# HELP vllm:cache_config_info Information of the LLMEngine CacheConfig\n"
    "# TYPE vllm:cache_config_info gauge\n"
    'vllm:cache_config_info{block_size="16",enable_prefix_caching="True",'
    'gpu_memory_utilization="0.85",kv_cache_max_concurrency="16.00390625",'
    'kv_cache_size_tokens="131104"} 1.0\n'
    'vllm:num_requests_running{model_name="Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ"} 0.0\n'
)

# --- the probe set ----------------------------------------------------------


def test_every_declared_field_is_present_and_every_null_states_why(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D2's three states, on the four fields nothing wrote before this module.

    An **absent** key means the record predates the contract, so a capture made
    from here on must never produce one — including for the fields this rig's
    endpoints do not answer, which is three of the four.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")

    for field in observed.PROBE_SET:
        assert field in block, f"{field} is absent, which D2 reads as 'predates'"
    reasons = block[observed.identity.REFUSALS]
    for field in observed.PROBE_SET:
        if block[field] is None:
            assert reasons.get(field), f"{field} is null with no stated reason"
        else:
            assert field not in reasons


# Seven checks stood here, and all seven were about the four declared fields as
# read off a native surface: quantization off `details.quantization_level` with
# a fallback to the listing row, the EFFECTIVE window off the residency listing
# rather than the trained one both describing calls reported, the refusal when
# the model was not resident, the pinned `num_ctx` branch, the concurrency
# refusal naming the daemon-wide setting that held the answer, and the seed
# refusal naming `llama-server`'s /slots on 127.0.0.1 where the answer actually
# was. That surface went with its backend on 2026-09-06; the checks and the
# readings behind them are in `archive/forensic-ollama/`.
#
# What they were protecting is not gone. The shape they held — every declared
# field present, every null carrying a reason that is about THIS engine — is
# pinned above by `test_every_declared_field_is_present_and_every_null_states_why`
# and below by the vLLM arm's own refusal checks, which is where the whole probe
# set is now answered or refused.


def test_no_runner_in_this_tree_sends_a_seed() -> None:
    """The half of "observed, never set" that a probe cannot prove.

    Built rather than grepped: what matters is the payload that leaves the
    process, and a payload assembled from a dict is not something a pattern
    over the source can be trusted about.
    """
    from mcgyvr.pool import Endpoint, Protocol
    from mcgyvr.runner import _RUNNERS, Request

    assert set(_RUNNERS) == set(Protocol), "a protocol with no runner is untested here"
    request = Request(prompt="p", max_output_tokens=16, system="s")
    for protocol, runner_class in _RUNNERS.items():
        endpoint = Endpoint(
            source="test",
            base_url="http://test:11434",
            protocol=protocol,
            max_parallel=1,
            credential_env=None,
        )
        payload = runner_class(endpoint)._payload("m", request)
        assert "seed" not in json.dumps(payload), (
            f"{runner_class.__name__} sends a seed. Greedy bypasses the sampler "
            "RNG, and supplying one is a different experiment (#276 item 9) — "
            "`observed.seed` records what the server holds, not what we set."
        )


def test_an_endpoint_that_answers_nothing_still_produces_the_whole_shape(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The degenerate arm.

    "The schema survives a protocol that answers almost nothing" means the file
    has the same keys and says why they are empty — not that it is absent.
    """
    _endpoint(observed, monkeypatch, None, None)
    block = observed.capture("http://srv2:8000", "some-model")

    assert block[observed.ENGINE] == observed.UNREACHABLE
    assert set(observed.PROBE_SET) <= set(block)
    assert all(block[f] is None for f in observed.PROBE_SET)
    reasons = block[observed.identity.REFUSALS]
    assert set(reasons) == set(observed.PROBE_SET)
    assert all("described itself at all" in reason for reason in reasons.values())
    assert block[observed.NATIVE] == {}


# --- the other engine, which answers the other half (#286, vLLM) -------------


def test_a_vllm_is_identified_and_never_read_as_an_ollama(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The engine decides what a refusal means, so it is on the block.

    Identified from what answers rather than from the port: `detect` guesses
    identity from a port because what it needs is the wire protocol, and this
    needs the server.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        version={"version": "0.11.0"},
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct")
    assert block[observed.ENGINE] == observed.VLLM
    assert "tags" not in block[observed.NATIVE]


def test_vllm_answers_the_window_ollama_cannot(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`max_model_len` IS the effective window — `--max-model-len` sets it.

    Both engines answer this field, and each from an endpoint the other does not
    have: ollama from `/api/ps` and only while the model is resident, vLLM from
    the model card and unconditionally. Measured 8192 on srv1 and 16384 on srv2,
    matching the flags each was launched with.
    """
    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert block["context_length"] == 8192
    assert "context_length" not in block.get(observed.identity.REFUSALS, {})


def test_vllm_refuses_the_quantization_ollama_answers(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The other half of the trade, and it refuses rather than guessing.

    `--quantization` is a launch flag the server does not report back, so it is
    unobtainable here — which is a different fact from "absent" and is stated
    as such.
    """
    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct")
    assert block["quantization"] is None
    assert "quantization" in block[observed.identity.REFUSALS]


def test_concurrency_refuses_on_vllm_and_never_takes_the_lookalike(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The capture refuses ``concurrency`` on vLLM and never takes the lookalike.

    `max_num_seqs` — the scheduler's batch width, which is what this field
    means — is not read from the server by the capture; the vLLM backend reads
    the launched width off the host instead (`launched_width` in
    `tools/bench/serving/backends/vllm.py`: the running process's argv, or the
    container's `Config.Cmd`).

    `kv_cache_max_concurrency` is right there in the metrics and looks like the
    answer. It is KV-cache capacity, and it can move OPPOSITE to the flag: a
    unit launched with a smaller `--max-num-seqs` can report a larger figure.
    A capture that took it would record a number that can get *smaller* as the
    real concurrency gets larger — which is why this asserts the refusal rather
    than a value.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")

    assert block["concurrency"] is None
    reason = block[observed.identity.REFUSALS]["concurrency"]
    assert "max_num_seqs" in reason
    assert "16.004" in reason and "5.314" in reason, (
        "the refusal must carry the measurement that refutes the lookalike, "
        "or the next lane re-derives it from the same tempting label"
    )
    # Captured raw regardless, so a later question is answerable off the run.
    assert "kv_cache_max_concurrency" in block[observed.NATIVE]["metrics"]


def test_dev_mode_is_what_makes_quantization_and_seed_observable(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The single biggest lever on how much of the probe set a vLLM answers.

    `/server_info` is gated behind `VLLM_SERVER_DEV_MODE=1`. With it, three of
    four fields are answered (measured `quantization=auto_awq`, `seed=0`,
    `max_seq_len=8192` on srv1 and 16384 on srv2). Without it, one is — and the
    refusals name the flag, so a reader learns the field is a fact about how
    the server was started rather than a limit of what vLLM can say.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
    )
    on = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert on["quantization"] == "auto_awq"
    assert on["seed"] == 0

    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    off = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert off["quantization"] is None
    assert off["seed"] is None
    reasons = off[observed.identity.REFUSALS]
    assert "VLLM_SERVER_DEV_MODE=1" in reasons["quantization"]
    assert "VLLM_SERVER_DEV_MODE=1" in reasons["seed"]
    # The window survives dev mode being off: /v1/models carries it either way.
    assert off["context_length"] == 8192


def test_an_unrecorded_seed_on_vllm_is_a_set_seed(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Measured: vLLM 0.26.0 defaults to `seed=0`, not to none.

    "Observed, never set" is a statement about what this tree DISPATCHES. It is
    not a statement about the server, and on this engine the server has one
    whether anybody asked for it — so a vLLM run whose seed went unrecorded was
    seeded, and the refusal has to say that rather than implying no seed exists.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert block["seed"] == 0

    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    off = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert "defaults to" in off[observed.identity.REFUSALS]["seed"]


def test_a_plain_openai_server_is_not_called_a_vllm(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """llama-server, LM Studio and TGI land here, and the block says so."""
    models = {"object": "list", "data": [{"id": "m", "object": "model"}]}
    _endpoint(observed, monkeypatch, None, None, models=models)
    block = observed.capture("http://rig:8080", "m")
    assert block[observed.ENGINE] == observed.OPENAI_COMPATIBLE
    assert block["context_length"] is None
    assert all(block[f] is None for f in observed.PROBE_SET)


def test_two_unmatched_cards_refuse_rather_than_pick_one(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Guessing which card the dispatch used is the substitute D2 forbids.

    One card and no id match is a different case: a served model's id is often
    the path it was loaded from rather than the name a config calls it, and
    there is nothing to be wrong about.
    """
    two = {
        "object": "list",
        "data": [
            {"id": "a", "owned_by": "vllm", "max_model_len": 4096},
            {"id": "b", "owned_by": "vllm", "max_model_len": 32768},
        ],
    }
    _endpoint(observed, monkeypatch, None, None, models=two)
    assert observed.capture("http://rig:8000", "c")["context_length"] is None

    one = {"object": "list", "data": [{"id": "a", "max_model_len": 4096}]}
    _endpoint(observed, monkeypatch, None, None, models=one)
    assert observed.capture("http://rig:8000", "c")["context_length"] == 4096


def test_every_engine_says_whether_it_has_been_run_live(observed: Any) -> None:
    """The contingency lives where the code is.

    The vLLM arm was built from documentation because no vLLM was reachable;
    the arm that was built against a live server on 2026-08-18 went with its
    backend on 2026-09-06. Measured and documented shapes are not the same
    evidence, so the difference is declared per engine — and a third arm cannot
    arrive unmarked, because this fails if one does.
    """
    for engine in observed.ENGINES:
        marked = (engine in observed.VERIFIED_LIVE) + (engine in observed.UNVERIFIED)
        assert marked == 1, (
            f"{engine!r} is in neither VERIFIED_LIVE nor UNVERIFIED, or in both. "
            "Say whether this module's shapes for it have been exercised "
            "against a live endpoint — a documented shape and a measured one "
            "are not the same evidence."
        )
    assert observed.VLLM in observed.VERIFIED_LIVE, (
        "vLLM was run against a live server on 2026-08-18 and every number "
        "this module states for it is a measurement; demoting it means "
        "deleting that evidence, not just moving a key."
    )


# --- redaction, on capture and before write ---------------------------------


def test_a_planted_secret_never_reaches_disk(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A comprehensive capture of a server's self-description is the risk.

    ``run.json`` holds one URL that one call redacts. This holds a server's
    whole self-description — on vLLM that is ``/server_info``'s ``vllm_config``,
    a 3,118-character Python repr on srv1 that names the checkpoint it loaded
    and every setting it was launched with, and a serving host can have any of
    it pointing at a private registry. The fixtures are assembled at runtime
    rather than written as literals: a secret-shaped literal in a tracked file
    is rejected by GitHub's push protection and flagged by this repo's own
    scanner, and the reassembled string exercises the scrub identically.
    """
    token = "ghp_" + "a" * 36
    key_id = "AKIA" + "B" * 16
    credentialed = "https://someone:hunter2@registry.example.com/qwen"
    server_info = {
        **VLLM_SERVER_INFO,
        "vllm_config": (
            f"model='{credentialed}', download_dir=None, "
            f"revision=None, hf_token={token}, "
            f"# pulled with {key_id}"
        ),
    }
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        version={"version": "0.26.0"},
        server_info=server_info,
        metrics=VLLM_METRICS,
    )

    written = observed.write(tmp_path, "http://srv1:8000", "m")
    assert written is not None
    text = written.read_text(encoding="utf-8")

    for secret in (token, key_id, "hunter2", "someone:hunter2"):
        assert secret not in text, f"{secret!r} reached disk"
    # Redacted, not deleted: the reader still learns a registry was involved.
    assert "registry.example.com" in text


def test_a_home_directory_prefix_is_reduced_and_the_blob_digest_is_kept(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A served checkpoint's path is a host path, and on a home-directory
    install it names a user.

    That is what goes. The digest under it is `sha256-<hex>`, which is a piece
    of weights identity and which stays — reducing the prefix must not reduce
    the thing a reader joins on. Measured shape: a local checkpoint under a
    user's cache, which is what `vllm_config` carries when the model was not
    loaded from a repository id.
    """
    blob = "/home/adar/.cache/models/blobs/sha256-29d8c98fa6b0"
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        version={"version": "0.26.0"},
        server_info={**VLLM_SERVER_INFO, "vllm_config": f"model='{blob}'"},
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://srv1:8000", "m")

    config = block[observed.NATIVE]["server_info"]["vllm_config"]
    assert "/home/adar/" not in config
    assert "/home/<redacted>/.cache/models/blobs/sha256-29d8c98fa6b0" in config


def test_redaction_reaches_a_string_nested_anywhere(observed: Any) -> None:
    """The risk is not at the top level — the Modelfile is one string in one key."""
    token = "xoxb-" + "1" * 20
    scrubbed = observed.scrub({"a": [{"b": {"c": [f"see {token}"]}}]})
    assert token not in json.dumps(scrubbed)


# --- comprehensive, without copying 7.7 MB into every run directory ----------


def test_a_long_array_is_recorded_as_its_count_and_its_digest(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A comprehensive capture must not copy megabytes into every run directory.

    The array that made this necessary was a tokenizer vocabulary — 151,936
    entries, 7.7 MB of JSON for the 1.5B — off a surface that is gone. The rule
    is not about that array: :func:`elide` walks whatever it is given, so any
    long list in any server's self-description is summarised the same way.
    Nothing a reader can act on is lost, because the summary carries
    :func:`identity.digest`, the same convention ``run.json`` uses.
    """
    # Past MAX_INLINE_ITEMS, so the length backstop fires. The by-name rule
    # is what caught the tokenizer arrays and is exercised below.
    long_list = [f"task{n}" for n in range(5000)]
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        version={"version": "0.26.0"},
        server_info={**VLLM_SERVER_INFO, "supported_tasks": long_list},
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://srv1:8000", "m")

    recorded = block[observed.NATIVE]["server_info"]["supported_tasks"]
    assert recorded[observed.ELIDED] is True
    assert recorded["count"] == 5000
    assert recorded["rule"] == "length"
    assert recorded["sha256"] == observed.identity.digest(long_list)
    # Under the threshold, so it stays as it was — a summary of a one-key
    # mapping would be less information, not more.
    assert (
        block[observed.NATIVE]["server_info"]["vllm_env"]
        == (VLLM_SERVER_INFO["vllm_env"])
    )


# `test_the_elided_digest_is_the_one_run_json_records` stood here. It held the
# join key claim by computing it both ways: the digest an elided array carries
# in the capture had to equal `probe_model`'s `vocabulary_sha256` in
# `run.json`, so a reader could rejoin the summarised array to the identity
# record without rehashing anything. Both sides were read off the same native
# surface, and `probe_model` now refuses all four of its fields — there is no
# second computation of that digest left to hold this one to. The convention
# itself is still pinned, one check up: an elided array carries
# `identity.digest` of what it replaced.

# --- one capture per directory ----------------------------------------------


def test_a_resume_keeps_the_capture_the_directory_was_opened_with(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Overwriting would lose the only record of what the endpoint said then.

    This block is compared by nothing, so it cannot refuse a resume — and a
    resume against a materially different server is refused by ``run.json``'s
    keyed drift, which is where a refusal belongs.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    first = observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b")
    assert first is not None
    before = first.read_text(encoding="utf-8")

    _endpoint(observed, monkeypatch, TAGS, {**SHOW, "details": {"family": "other"}})
    assert observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b") is None
    assert first.read_text(encoding="utf-8") == before


def test_a_probe_that_cannot_reach_anything_still_writes(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A capture that threw would be the worst of both: no rows AND no record."""

    def boom(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("the fetchers swallow their own failures")

    monkeypatch.setattr(observed.identity, "_get_json", boom)
    monkeypatch.setattr(observed.identity, "_post_json", boom)
    written = observed.write(tmp_path / "fresh", "http://nothing:1", "m")
    assert written is not None and written.is_file()


# --- nothing reads it -------------------------------------------------------

#: Where the name may appear. The writer, the contract module that explains the
#: state its four fields are now in, and this file. The two runner call sites go
#: through `observed_module.write` and never name the file, which is why they
#: are not here.
NAMES_THE_FILE = {
    "tools/bench/observed.py",
    "tools/bench/identity.py",
    "tests/test_bench_observed.py",
}


def test_nothing_outside_the_writer_names_the_file() -> None:
    """The acceptance property that is about the guard path, not the content.

    A field in this block is comprehensive *because* nobody admitted it. Wiring
    a guard to one would be a comparison on an unadmitted field — the failure
    D7 separates the two blocks to prevent — so the check is that the
    name does not spread, and the allow-list above is the thing a future lane
    has to argue with.
    """
    found = subprocess.run(
        ["git", "grep", "-l", "observed.json", "--", "src/", "tools/", "tests/"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    named = {line for line in found.stdout.splitlines() if line}
    assert named <= NAMES_THE_FILE, (
        f"{sorted(named - NAMES_THE_FILE)} name observed.json. Nothing reads "
        "this block for comparison (D7): a field in it is "
        "comprehensive because nobody admitted it, and promotion into "
        "identity.KEY is the owner's."
    )


def test_the_contract_module_records_the_landed_state(observed: Any) -> None:
    """#286's item 7: the four say what is true now, and did not move to #276's.

    `AWAITING_ADMISSION` means "#276's rule has not admitted it". #276's rule is
    not these fields' promotion path — D7 is — so they get their own reason
    rather than being folded into a queue they are not in.
    """
    identity = observed.identity
    for field in observed.PROBE_SET:
        assert identity.PENDING_REASON[field] == identity.CAPTURED_IN_OBSERVED
        assert field in identity.RECORDED
        assert field not in identity.KEY
    assert not hasattr(identity, "AWAITING_PROBE_SET"), (
        "the third state is gone: nothing in the repository is waiting on a "
        "writer for these four any more."
    )


# --- what the review found, pinned so it cannot come back -------------------


def test_a_base_url_that_already_ends_in_v1_is_not_doubled(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A `base_url` that ends in `/v1` is probed at `/v1`, never at `/v1/v1`.

    A `base_url` copied from a hosted provider's own page carries `/v1`, and
    `runner._url_for` absorbs it too. Concatenating instead would
    404 a healthy server on every probe and record it as "nothing there
    described itself at all".
    """
    asked: list[str] = []

    def get(url: str, *, timeout: float) -> Any:
        asked.append(url)
        return None

    monkeypatch.setattr(observed.identity, "_get_json", get, raising=True)
    monkeypatch.setattr(
        observed.identity, "_post_json", lambda url, body, *, timeout: None
    )
    monkeypatch.setattr(observed, "_get_text", lambda url, *, timeout: None)
    observed.capture("https://api.example.com/v1", "m")

    assert "https://api.example.com/v1/models" in asked
    assert not [url for url in asked if "/v1/v1/" in url]

    # The doubling check above passes even with the bug it was written for:
    # /v1/models is the one path the old rule handled. The six root-level
    # entries in VLLM_READS are where it went wrong, so name them.
    for path in ("/version", "/server_info", "/load", "/is_sleeping"):
        assert f"https://api.example.com{path}" in asked, path
        assert f"https://api.example.com/v1{path}" not in asked, path


def test_a_capture_never_raises_however_bad_the_server_text_is(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """`bundle.redact` reads `urlsplit(...).port`, which RAISES on a bad port.

    Fine for the one URL `run.json` holds; not fine over every string a server
    sent. `record_run` calls the writer after `run.json` is already on disk, so
    an exception here meant a traceback and zero rows — the exact "worst of
    both" the docstring promises to avoid. An unparseable candidate is redacted
    wholesale, because it cannot be shown to be safe.
    """
    hostile = {
        "details": {},
        "modelfile": "FROM registry://u:p@host:99999/blob\n",
        "license": "see ftp://a:b@[unbalanced/x",
    }
    _endpoint(observed, monkeypatch, TAGS, hostile, ps=PS)

    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    text = json.dumps(block)
    assert "99999" not in text and "u:p@" not in text

    # And the writer is belt-and-braces: even a capture that somehow throws must
    # leave a file rather than kill the sweep.
    monkeypatch.setattr(
        observed, "capture", lambda *a, **k: (_ for _ in ()).throw(RuntimeError("boom"))
    )
    written = observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b")
    assert written is not None
    recorded = json.loads(written.read_text())[observed.CAPTURES][observed.AT_OPEN][
        observed.NATIVE_SOURCE
    ]
    assert "boom" in recorded[observed.identity.REFUSALS]["seed"]


def test_a_non_vllm_server_is_never_told_vllm_facts_about_itself(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A null must carry a TRUE reason, and these reasons are vLLM measurements.

    The realistic path is not a hypothetical: an ollama whose `/api/*` calls
    fail transiently falls through to the served arm — ollama does serve
    `/v1/models` — is identified as `openai-compatible`, and would have had
    `/server_info`, `VLLM_SERVER_DEV_MODE=1` and "vLLM 0.26.0 defaults to
    seed=0" written to its disk as the stated reasons for its nulls.
    """
    plain = {"object": "list", "data": [{"id": "m", "object": "model"}]}
    _endpoint(observed, monkeypatch, None, None, models=plain)
    block = observed.capture("http://rig:8080", "m")

    assert block[observed.ENGINE] == observed.OPENAI_COMPATIBLE
    reasons = block[observed.identity.REFUSALS]
    for field, reason in reasons.items():
        for claim in ("VLLM_SERVER_DEV_MODE", "/server_info", "vLLM 0.26.0"):
            assert claim not in reason, f"{field} asserts {claim!r} about a non-vLLM"
    assert all(
        "nothing here has been measured against it" in r for r in reasons.values()
    )


def test_the_long_timeout_is_spent_only_on_the_call_that_earned_it(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A dozen probes at the /api/show budget put six minutes before a sweep.

    `CAPTURE_TIMEOUT_S` is spent on one call — `/metrics`, which is 58 KB of
    Prometheus text. Everything else returns kilobytes at the discovery budget.
    The call that originally earned the long budget was a POST returning the
    tokenizer arrays, and it went with its surface on 2026-09-06; what the
    check protects is unchanged, which is that a second long call cannot be
    added in front of a sweep without someone noticing.
    """
    seen: list[tuple[str, float]] = []

    def note_get(url: str, *, timeout: float) -> None:
        seen.append((url, timeout))
        return None

    def note_post(url: str, body: dict[str, Any], *, timeout: float) -> None:
        seen.append((url, timeout))
        return None

    monkeypatch.setattr(observed.identity, "_get_json", note_get, raising=True)
    monkeypatch.setattr(observed.identity, "_post_json", note_post)
    monkeypatch.setattr(observed, "_get_text", note_get, raising=True)
    observed.capture("http://srv2:11434", "m")

    long_calls = [url for url, timeout in seen if timeout >= observed.CAPTURE_TIMEOUT_S]
    assert long_calls == ["http://srv2:11434/metrics"]
    assert all(
        timeout == observed.DISCOVERY_TIMEOUT_S
        for url, timeout in seen
        if url != "http://srv2:11434/metrics"
    )


# --------------------------------------------------------------------------
# #350: the width the record already held, and the width only the client knows.
#
# `concurrency` in PROBE_SET is refused on both engines, correctly — it is on no
# network surface either serves. The ollama refusal ends by naming where the
# answer is, `tools/bench/serving/`, and the `host` block written beside it in
# the same file is produced by that module with that access. These checks hold
# the meeting point: the number reaches the record, the native refusal is left
# exactly as it was, and the two bounds on the realised batch stay two fields.
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def pin() -> Any:
    return by_path("serving_pin", REPO / "tools" / "bench" / "serving" / "pin.py")


def test_the_served_width_is_read_off_the_host_config(pin: Any) -> None:
    """`-np` reaches the record under a name that does not name an engine."""
    reading = pin.width("ollama", "srv1", {"semantic": {"n_parallel": 2}}, None)
    assert reading["value"] == 2
    assert reading["source"] == "host:n_parallel"
    assert "refused" not in reading


def test_two_host_sources_that_disagree_about_the_width_are_refused(
    pin: Any,
) -> None:
    """The flag and the slot count must agree; resolving them would pick one.

    `vllm.declared_slots` already applies this rule to its own pair. A width is
    a fact about the running server, and two contradictory readings of it mean
    the thing being described is not what one of them describes.
    """
    reading = pin.width(
        "ollama", "srv1", {"semantic": {"n_parallel": 2, "total_slots": 1}}, None
    )
    assert reading["value"] is None
    assert "2" in reading["refused"] and "1" in reading["refused"]


def test_a_config_with_no_width_refuses_with_the_config_s_own_reason(
    pin: Any,
) -> None:
    """A refusal that drops the cause underneath it is a refusal twice over."""
    reading = pin.width("ollama", "srv1", {"refused": "no model is resident"}, None)
    assert reading["value"] is None
    assert "no model is resident" in reading["refused"]


def test_the_vllm_width_comes_from_the_launcher_read_not_from_the_wire(
    pin: Any,
) -> None:
    """`--max-num-seqs` is in argv or in the container's Cmd, and nowhere else.

    A server launched at 8 reports `kv_cache_max_concurrency` 16.004, so the
    lookalike moves opposite to the flag and is never substituted. This asserts
    the value arrives from `launched_width` and carries where it was found.
    """

    class _Backend:
        @staticmethod
        def launched_width(host: str) -> dict[str, Any]:
            return {"value": 8, "source": "process"}

    reading = pin.width("vllm", "srv1", {}, _Backend)
    assert reading == {"value": 8, "source": "host:process"}


def test_a_vllm_host_that_will_not_say_its_width_refuses_with_a_reason(
    pin: Any,
) -> None:
    class _Backend:
        @staticmethod
        def launched_width(host: str) -> dict[str, Any]:
            return {"value": None, "source": None}

    reading = pin.width("vllm", "srv1", {}, _Backend)
    assert reading["value"] is None
    assert "max-num-seqs" in reading["refused"]


def test_a_host_with_no_serving_process_still_carries_the_width_key(
    pin: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An ABSENT key means the record predates the contract (D2).

    The no-process path returns early, and that early return is exactly where a
    key quietly stops being written for one branch of one engine.
    """
    monkeypatch.setattr(
        pin, "same_machine", lambda host, endpoint: {"held": True}, raising=True
    )
    monkeypatch.setattr(
        pin, "instance", lambda host, pattern: {"present": False}, raising=True
    )
    block = pin.host_block("http://srv1:11434")
    assert block["width"]["value"] is None
    assert block["width"]["refused"]


def test_the_served_width_reaches_the_record_the_native_block_refused(
    observed: Any,
) -> None:
    """The number the record already held, in the field declared for it."""
    resolved = observed.resolve({"width": {"value": 2, "source": "host:n_parallel"}}, 1)
    assert resolved[observed.SERVED_WIDTH]["value"] == 2
    assert resolved[observed.DISPATCH_MAX_PARALLEL]["value"] == 1


def test_the_two_widths_are_two_fields_and_neither_stands_in_for_the_other(
    observed: Any,
) -> None:
    """A server width of 4 dispatched at 1 must read as 4 and 1, never as one.

    This is the rule carried across: a per-process figure is not the
    card, and the width a server was started at is not the width a client used.
    """
    resolved = observed.resolve({"width": {"value": 4, "source": "host:n_parallel"}}, 1)
    assert resolved[observed.SERVED_WIDTH]["value"] == 4
    assert resolved[observed.DISPATCH_MAX_PARALLEL]["value"] == 1
    assert observed.SERVED_WIDTH != observed.DISPATCH_MAX_PARALLEL


def test_no_host_block_leaves_the_served_width_null_with_a_reason(
    observed: Any,
) -> None:
    resolved = observed.resolve({}, 1)
    served = resolved[observed.SERVED_WIDTH]
    assert served["value"] is None
    assert served[observed.identity.REFUSALS]


def test_a_runner_that_passes_no_dispatch_width_is_recorded_as_a_refusal(
    observed: Any,
) -> None:
    """Not a zero and not a one. The default must not look like a measurement."""
    resolved = observed.resolve({"width": {"value": 2}}, None)
    dispatch = resolved[observed.DISPATCH_MAX_PARALLEL]
    assert dispatch["value"] is None
    assert dispatch[observed.identity.REFUSALS]


def test_the_resolved_block_never_writes_into_the_native_block(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A host reading under the `native` label destroys the file's one axis.

    The sources exist so a reader can tell what kind of evidence a number is.
    A width that arrived over ssh must not appear inside the block that means
    "what the endpoint said about itself".
    """
    monkeypatch.setattr(
        observed,
        "capture",
        lambda endpoint, model, timeout=0.0: {
            "endpoint": endpoint,
            "model": model,
            "concurrency": None,
            observed.identity.REFUSALS: {"concurrency": "not on any endpoint"},
        },
        raising=True,
    )
    observed.write(
        tmp_path,
        "http://srv1:11434",
        "m",
        host={"width": {"value": 2, "source": "host:n_parallel"}},
        dispatch_max_parallel=1,
    )
    written = json.loads((tmp_path / observed.OBSERVED_FILE).read_text())
    capture = written[observed.CAPTURES][observed.AT_OPEN]
    native = capture[observed.NATIVE_SOURCE]
    assert native["concurrency"] is None
    assert native[observed.identity.REFUSALS]["concurrency"]
    assert capture[observed.RESOLVED_SOURCE][observed.SERVED_WIDTH]["value"] == 2


@pytest.mark.parametrize("rig", ["tools/breadth/measure.py", "tools/bundle/measure.py"])
def test_both_runners_pass_the_width_they_dispatched_at(rig: str) -> None:
    """The one half of the pair no probe can recover.

    A server cannot see how many requests a client chose to keep in flight, so
    if the call site does not say it, nothing does — and the field would read
    `null` on every run while the runner knew the answer the whole time. Held
    against the source rather than a captured file because that is where it
    would be dropped.
    """
    source = (REPO / rig).read_text(encoding="utf-8")
    assert "dispatch_max_parallel=worker.as_endpoint().max_parallel" in source


# --------------------------------------------------------------------------
# #349: an empty host block meant four different things.
#
# "There is no machine to log into", "the dispatch address is loopback", "the
# name did not resolve" and "the probe raised" all arrived as `{}`. The last of
# those is a BROKEN reading and the first three are ordinary absences, so the
# one value a reader could not act on was the one that mattered most. The same
# collapse the harness refuses on purpose at `gpu_idle` and at the compute-apps
# sentinel, so that an unread card cannot parse as an empty one.
# --------------------------------------------------------------------------


def test_an_endpoint_with_no_hostname_says_so_rather_than_reading_empty(
    pin: Any,
) -> None:
    block = pin.host_block("not-a-url")
    assert block["reason"] == pin.NO_HOSTNAME
    assert "no hostname" in block["refused"]


def test_a_loopback_endpoint_is_its_own_reason_not_an_absent_host(
    pin: Any,
) -> None:
    """Loopback names whatever box resolved it, which is a different fact.

    `same_machine` cannot refute a claim it cannot address, and that is worth
    saying out loud: the readings may be perfectly good and simply unbindable.
    """
    block = pin.host_block("http://localhost:11434")
    assert block["reason"] == pin.LOOPBACK
    assert "loopback" in block["refused"]


def test_a_name_that_will_not_resolve_carries_the_resolver_s_own_reason(
    pin: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A refusal that drops the cause underneath it is a refusal twice over."""
    monkeypatch.setattr(
        pin,
        "same_machine",
        lambda host, endpoint: {"held": None, "why": "srv9 did not resolve: no DNS"},
        raising=True,
    )
    block = pin.host_block("http://srv9:11434")
    assert block["reason"] == pin.UNRESOLVABLE
    assert "no DNS" in block["refused"]
    assert block["machine"]["held"] is None


def test_a_probe_that_raises_reaches_the_record_instead_of_the_floor(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The `except` keeps its promise never to raise, and stops swallowing.

    A sweep must never fail because a capture did. That is not the same thing
    as a broken probe being indistinguishable from a machine there was nothing
    to read, which is what a bare `{}` made it.
    """
    breadth = by_path("breadth_measure", REPO / "tools" / "breadth" / "measure.py")

    def explode(endpoint: str) -> dict[str, Any]:
        raise RuntimeError("pin.py would not import")

    monkeypatch.setattr(breadth, "_bench_observed", lambda: None, raising=False)
    module = types.SimpleNamespace(host_block=explode)
    monkeypatch.setitem(sys.modules, "serving_pin", module)
    block = breadth._host_block("http://srv1:11434")
    assert block["reason"] == "probe_failed"
    assert "RuntimeError" in str(block["refused"])
    assert "would not import" in str(block["refused"])


def test_every_way_of_holding_no_readings_is_told_apart_from_the_others(
    pin: Any,
) -> None:
    """The property, stated once: four states, four values, no collisions.

    Written as a set comparison rather than four assertions because the defect
    was not any one arm being wrong — it was two arms being EQUAL.
    """
    reasons = {
        pin.host_block("not-a-url")["reason"],
        pin.host_block("http://localhost:11434")["reason"],
        pin.unread(pin.UNRESOLVABLE, "x")["reason"],
        "probe_failed",
    }
    assert len(reasons) == 4
    assert reasons == {
        pin.NO_HOSTNAME,
        pin.LOOPBACK,
        pin.UNRESOLVABLE,
        pin.PROBE_FAILED,
    }


def test_a_block_that_holds_no_readings_still_carries_the_width_key(
    pin: Any, observed: Any
) -> None:
    """The shape must not fork by failure mode.

    A consumer reaching for the width should not have to know which of the four
    produced the block it is reaching into — that is how a reader comes to
    write `or 0` and put a number nobody measured on disk.
    """
    for block in (
        pin.host_block("not-a-url"),
        pin.host_block("http://localhost:11434"),
        pin.unread(pin.UNRESOLVABLE, "the name did not resolve"),
    ):
        assert "width" in block, "the key must be there before anyone reaches"
        resolved = observed.resolve(block, 1)
        served = resolved[observed.SERVED_WIDTH]
        assert served["value"] is None
        # The block's OWN reason, not the generic one `resolve` falls back to
        # when no host block was captured at all. Asserting merely that SOME
        # refusal is present passes on the fallback, which is how dropping the
        # key from `unread` survived this check the first time it was swept.
        assert served[observed.identity.REFUSALS] == block["refused"]


def test_a_hosted_endpoint_that_resolves_is_not_one_of_the_empty_states(
    pin: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Corrects the claim #349 was filed on, which named it as a fourth `{}`.

    Measured: an endpoint whose name resolves goes past all three early
    returns and produces a full block whose `machine.held` is False and whose
    `why` says the dispatch address is not this host's. That is a stronger
    record than an empty one, and it was already correct before this change.
    """
    monkeypatch.setattr(
        pin,
        "same_machine",
        lambda host, endpoint: {
            "held": False,
            "endpoint_resolves_to": ["192.0.2.1"],
            "why": "the dispatch address is NOT among this host's addresses",
        },
        raising=True,
    )
    monkeypatch.setattr(
        pin, "instance", lambda host, pattern: {"present": False}, raising=True
    )
    block = pin.host_block("http://192.0.2.1:11434")
    assert "reason" not in block
    assert block["machine"]["held"] is False


def test_the_two_rigs_read_the_host_the_same_way() -> None:
    """`_host_block` is duplicated in both rigs, and nothing held it identical.

    It cannot move into `observed`: that module gathers no host readings by
    design, which is what lets it work unchanged against an endpoint nobody can
    log into. And it cannot import `pin`'s vocabulary, because one of the cases
    it reports is `pin` itself failing to load. So the copies stay, and this is
    what stops them from drifting into two different answers to one question.

    Compared as parsed code rather than as text: a comment may differ between
    the two files, and behaviour may not.
    """
    parsed = []
    for rig in ("tools/breadth/measure.py", "tools/bundle/measure.py"):
        tree = ast.parse((REPO / rig).read_text(encoding="utf-8"))
        found = [
            node
            for node in tree.body
            if isinstance(node, ast.FunctionDef) and node.name == "_host_block"
        ]
        assert len(found) == 1, rig
        parsed.append(ast.unparse(found[0]))
    assert parsed[0] == parsed[1]


# --- #353: the third term, measured on one engine and refused on the other ---
#
# `dispatch_max_parallel` bounds the realised batch only if this run was the
# sole client, and nothing established that. It does now, on vLLM: the server's
# own `vllm:request_success_total`, read at open and at close. Measured on srv1
# 2026-08-23 against vllm 0.26.0 — five `/v1/completions` moved it by exactly
# five, and `/health`, `/metrics`, `/ping`, `/v1/models`, three kinds of failed
# request and two full `capture()` passes moved it by none. On ollama there is
# no counter to difference and the field refuses with where the answer would be.

#: srv1's own `/metrics`, cut to the series under test and to two label sets of
#: the one that is summed. The zero-valued reasons are kept because they are
#: what a real body carries: vLLM emits every `finished_reason` from the start.
_METRICS_AT_OPEN = """\
# HELP vllm:num_requests_running Number of requests in model execution batches.
# TYPE vllm:num_requests_running gauge
vllm:num_requests_running{engine="0",model_name="m"} 0.0
# HELP vllm:request_success_total Count of successfully processed requests.
# TYPE vllm:request_success_total counter
vllm:request_success_total{engine="0",finished_reason="stop",model_name="m"} 3.0
vllm:request_success_total{engine="0",finished_reason="length",model_name="m"} 1.0
vllm:request_success_total{engine="0",finished_reason="abort",model_name="m"} 0.0
# HELP http_requests_total Total HTTP requests
# TYPE http_requests_total counter
http_requests_total{handler="/v1/models",method="GET",status="2xx"} 4.0
"""

_METRICS_AT_CLOSE = _METRICS_AT_OPEN.replace(
    'finished_reason="stop",model_name="m"} 3.0',
    'finished_reason="stop",model_name="m"} 9.0',
).replace(
    'finished_reason="abort",model_name="m"} 0.0',
    'finished_reason="abort",model_name="m"} 2.0',
)


def _vllm_block(metrics: str | None) -> dict[str, Any]:
    """A capture the way `capture()` returns one, cut to what #353 reads."""
    native: dict[str, Any] = {"models": {"data": []}}
    if metrics is not None:
        native["metrics"] = metrics
    return {
        "endpoint": "http://srv1:8000",
        "model": "m",
        "engine": "vllm",
        "native": native,
    }


def _write_pair(
    observed: Any,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    *,
    at_open: dict[str, Any],
    at_close: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Both captures through the real `write`, returning the file it wrote."""
    blocks = [at_open] if at_close is None else [at_open, at_close]
    monkeypatch.setattr(
        observed,
        "capture",
        lambda endpoint, model, timeout=0.0: blocks.pop(0),
        raising=True,
    )
    for when in (observed.AT_OPEN, observed.AT_CLOSE)[: 1 if at_close is None else 2]:
        observed.write(
            tmp_path, "http://srv1:8000", "m", when=when, dispatch_max_parallel=1
        )
    written: dict[str, Any] = json.loads(
        (tmp_path / observed.OBSERVED_FILE).read_text(encoding="utf-8")
    )
    return written


def test_the_server_counter_states_what_the_server_finished_in_the_window(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The measurement, end to end, through the writer the runners call.

    4 at open and 12 at close is a delta of 8 — and 8 is what the SERVER did,
    not what this run did. The subtraction that makes it foreign traffic needs
    the run's own dispatched rows, which live in `run.json` beside this file and
    are deliberately not passed here (that would touch both runner call sites,
    which are SURFACE). What is recorded is the term nobody else can supply.
    """
    written = _write_pair(
        observed,
        tmp_path,
        monkeypatch,
        at_open=_vllm_block(_METRICS_AT_OPEN),
        at_close=_vllm_block(_METRICS_AT_CLOSE),
    )
    closed = written[observed.CAPTURES][observed.AT_CLOSE][observed.RESOLVED_SOURCE]
    term = closed[observed.SERVER_COMPLETIONS]
    assert term["at_open"] == 4.0 and term["at_close"] == 12.0
    assert term["value"] == 8.0
    assert term["counter"] == observed.VLLM_COMPLETIONS_SERIES
    assert term["window"] == f"{observed.AT_OPEN} to {observed.AT_CLOSE}"


def test_the_counter_is_summed_over_every_reason_a_request_can_end_for(
    observed: Any,
) -> None:
    """One line of this series is a fraction of the count, never the count.

    vLLM emits `vllm:request_success_total` once per `finished_reason` — stop,
    length, abort, error, repetition on the 0.26.0 build. Reading the first
    line, or the `stop` line, would undercount every run that ever hit a
    length cap, and undercounting foreign traffic is the direction that turns
    a contaminated run into a clean-looking one.
    """
    assert (
        observed._counter_total(_METRICS_AT_OPEN, "vllm:request_success_total") == 4.0
    )
    assert (
        observed._counter_total(_METRICS_AT_CLOSE, "vllm:request_success_total") == 12.0
    )


def test_a_series_whose_name_merely_starts_the_same_is_not_added_in(
    observed: Any,
) -> None:
    """`startswith` over a metric name is a bug waiting for a longer name.

    Prometheus names nest by convention — a `_bytes` or `_seconds` sibling of
    any counter is an ordinary thing for a build to add — and summing one into
    the other would inflate the window silently, which reads as foreign traffic
    that was never there.
    """
    body = (
        'vllm:request_success_total{finished_reason="stop"} 2.0\n'
        'vllm:request_success_total_bytes{finished_reason="stop"} 999.0\n'
    )
    assert observed._counter_total(body, "vllm:request_success_total") == 2.0


def test_an_engine_with_no_counter_refuses_and_names_where_the_answer_would_be(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The reason is a fact about the ENGINE rather than about us.

    "No route" and "we did not look" are the two states this field exists to
    keep apart, so a capture that holds no counter refuses and says which
    engine answered — an `openai-compatible` server is llama-server, LM Studio
    or TGI, and none of them serves the series vLLM does. Every non-vLLM server
    gets the same generic refusal.
    """
    written = _write_pair(
        observed,
        tmp_path,
        monkeypatch,
        at_open={"engine": "openai-compatible", "native": {}},
        at_close={"engine": "openai-compatible", "native": {}},
    )
    closed = written[observed.CAPTURES][observed.AT_CLOSE][observed.RESOLVED_SOURCE]
    term = closed[observed.SERVER_COMPLETIONS]
    assert term["value"] is None
    reason = term[observed.identity.REFUSALS]
    assert "openai-compatible" in reason, (
        f"the refusal does not name the engine it is a fact about: {reason}"
    )
    assert "not a counter reading zero" in reason, (
        f"a refusal that reads as a zero is the defect: {reason}"
    )


def test_an_open_capture_keeps_its_reading_and_says_it_cannot_difference_yet(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The near edge of the window is the reading taken then, not one taken now.

    A run whose file holds only an open capture did not finish, and this is what
    that looks like: a number, and a refusal that says what is missing is the
    other edge rather than the counter.
    """
    written = _write_pair(
        observed, tmp_path, monkeypatch, at_open=_vllm_block(_METRICS_AT_OPEN)
    )
    opened = written[observed.CAPTURES][observed.AT_OPEN][observed.RESOLVED_SOURCE]
    term = opened[observed.SERVER_COMPLETIONS]
    assert term["value"] is None
    assert term["reading"] == 4.0
    assert "nothing to difference against" in term[observed.identity.REFUSALS]


def test_a_counter_that_was_not_read_is_never_a_counter_reading_zero(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The whole failure mode of this issue, in the one place it can enter.

    A vLLM whose `/metrics` did not come back must not resolve to a delta of
    zero, which reads as measured sole-clientness. `_counter_total` answers
    `None` for an absent body and for a body without the series, and both are
    refusals here.
    """
    written = _write_pair(
        observed,
        tmp_path,
        monkeypatch,
        at_open=_vllm_block(None),
        at_close=_vllm_block('vllm:num_requests_running{engine="0"} 0.0\n'),
    )
    for when in (observed.AT_OPEN, observed.AT_CLOSE):
        term = written[observed.CAPTURES][when][observed.RESOLVED_SOURCE][
            observed.SERVER_COMPLETIONS
        ]
        assert term["value"] is None, when
        assert observed.identity.REFUSALS in term, when
    assert observed._counter_total(None, "vllm:request_success_total") is None
    assert observed._counter_total("", "vllm:request_success_total") is None


def test_the_third_term_is_a_count_or_a_refusal_and_never_a_verdict(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`sole_client: true` because nothing was detected is what must not exist.

    The field is named for what it holds — a count in a window — and carries no
    boolean anywhere in it, on either engine, in either capture. A reader who
    wants the verdict does the subtraction the note spells out, against a term
    this module does not have.
    """
    for block in (_vllm_block(_METRICS_AT_CLOSE), {"engine": "ollama", "native": {}}):
        written = _write_pair(
            observed,
            tmp_path / str(id(block)),
            monkeypatch,
            at_open=dict(block),
            at_close=dict(block),
        )
        for when in (observed.AT_OPEN, observed.AT_CLOSE):
            resolved = written[observed.CAPTURES][when][observed.RESOLVED_SOURCE]
            term = resolved[observed.SERVER_COMPLETIONS]
            assert not any(isinstance(v, bool) for v in term.values()), term
            assert "sole_client" not in json.dumps(resolved)


def test_a_window_with_no_near_edge_refuses_instead_of_reading_zero(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The asymmetric case, and the one a mutant found nothing guarding.

    A server that was unreachable at open and answered at close leaves a close
    reading with nothing to subtract. The tempting value is the close reading
    itself, or zero; both are numbers nobody measured. A window needs two
    edges, and a run that has only one is a run that did not finish the way
    this block assumes.
    """
    written = _write_pair(
        observed,
        tmp_path,
        monkeypatch,
        at_open=_vllm_block(None),
        at_close=_vllm_block(_METRICS_AT_CLOSE),
    )
    term = written[observed.CAPTURES][observed.AT_CLOSE][observed.RESOLVED_SOURCE][
        observed.SERVER_COMPLETIONS
    ]
    assert term["value"] is None
    assert term["reading"] == 12.0, "the close reading is kept, it is just not a delta"
    assert "no near edge" in term[observed.identity.REFUSALS]
