#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv1-01-rerun1: cold start c1 of srv1_35b_maxctx (a-solo), the one extra cold start for room of srv1-01; the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv1-c1-srv1_35b_maxctx-rerun1.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" rig-id-relock-srv1-c1-srv1_35b_maxctx-rerun1.json srv1_35b_maxctx "$@"
