#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv1-02: cold start c1 of srv1_deepseek (b-small); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv1-c1-srv1_deepseek.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" rig-id-relock-srv1-c1-srv1_deepseek.json srv1_deepseek "$@"
