#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv1-13: run r2 of the move b-big -> b-small on srv1; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv1-r2-b-big-to-b-small.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" rig-id-relock-srv1-r2-b-big-to-b-small.json srv1 b-big b-small "$@"
