#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv2-01-retry1: cold start c1 of srv2_35b_256k (a-solo), the one retry of srv2-01; the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv2-c1-srv2_35b_256k-retry1.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" rig-id-relock-srv2-c1-srv2_35b_256k-retry1.json srv2_35b_256k "$@"
