#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv2-21: cold start c3 of srv2_80b (b-big); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv2-c3-srv2_80b.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" rig-id-relock-srv2-c3-srv2_80b.json srv2_80b "$@"
