#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv2-24: run r2 of the move b-small -> b-big on srv2; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv2-r2-b-small-to-b-big.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" rig-id-relock-srv2-r2-b-small-to-b-big.json srv2 b-small b-big "$@"
