#!/usr/bin/env bash
# lock-fleets use rig-id-relock, entry srv2-25: run r2 of the move b-big -> b-small on srv2; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: rig-id-relock-srv2-r2-b-big-to-b-small.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" rig-id-relock-srv2-r2-b-big-to-b-small.json srv2 b-big b-small "$@"
