#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv1-03: cold start c1 of srv1_35b_b (b-big); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv1-c1-srv1_35b_b.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" mtp-ornith-srv1-c1-srv1_35b_b.json srv1_35b_b "$@"
