#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv1-07: cold start c3 of srv1_35b_maxctx (a-solo); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv1-c3-srv1_35b_maxctx.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" mtp-ornith-srv1-c3-srv1_35b_maxctx.json srv1_35b_maxctx "$@"
