#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv1-10: run r1 of the move b-small -> b-big on srv1; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv1-r1-b-small-to-b-big.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" mtp-ornith-srv1-r1-b-small-to-b-big.json srv1 b-small b-big "$@"
