#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv1-15: run r3 of the move b-big -> b-small on srv1; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv1-r3-b-big-to-b-small.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" mtp-ornith-srv1-r3-b-big-to-b-small.json srv1 b-big b-small "$@"
