#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv2-07: cold start c1 of srv2_80b (b-big); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv2-c1-srv2_80b.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" mtp-ornith-srv2-c1-srv2_80b.json srv2_80b "$@"
