#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv2-09: cold start c2 of srv2_35b_256k (a-solo); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv2-c2-srv2_35b_256k.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" mtp-ornith-srv2-c2-srv2_35b_256k.json srv2_35b_256k "$@"
