#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv2-24: cold start c3 of srv2_ornith_mtp (c-mtp); the body is _unit.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv2-c3-srv2_ornith_mtp.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_unit.sh" mtp-ornith-srv2-c3-srv2_ornith_mtp.json srv2_ornith_mtp "$@"
