#!/usr/bin/env bash
# lock-fleets use mtp-ornith, entry srv2-26: run r1 of the move b-big -> b-small on srv2; the body is _move.sh. Generated by records/measurements/lock-fleets/plan.py.
# RUN_ARTIFACTS: mtp-ornith-srv2-r1-b-big-to-b-small.json
exec bash "$(dirname -- "${BASH_SOURCE[0]}")/../_move.sh" mtp-ornith-srv2-r1-b-big-to-b-small.json srv2 b-big b-small "$@"
