import assert from "node:assert/strict";
import { bitAt, findFreeRun, occupyRun } from "./solution.ts";

assert.equal(findFreeRun([0], 32, 1), 0, "empty map allocates at zero");
assert.equal(findFreeRun([9], 32, 2), 1, "gap between occupied blocks");
assert.equal(findFreeRun([2147483647, 0], 64, 3), 31, "run crossing a word boundary");
assert.equal(findFreeRun([4294967295], 32, 1), -1, "full map has no run");
assert.equal(findFreeRun([0], 10, 10), 0, "run exactly filling the capacity");
assert.equal(findFreeRun([0], 10, 11), -1, "run longer than the capacity");
assert.equal(findFreeRun([51], 32, 2), 2, "smallest start wins");
assert.equal(findFreeRun([4294967295, 6], 64, 2), 35, "gap inside the second word");
assert.equal(findFreeRun(occupyRun([0, 0], 0, 40), 64, 3), 40, "search after occupation");
assert.equal(bitAt([6], 1), 1, "set bit reads one");
assert.equal(bitAt([0, 8], 35), 1, "bit in the second word");
assert.deepEqual(occupyRun([0], 2, 3), [28], "run marked in one word");
assert.deepEqual(occupyRun([0, 0], 30, 4), [3221225472, 3], "run marked across words");
const base = [0];
occupyRun(base, 0, 1);
assert.deepEqual(base, [0], "occupation does not modify its argument");
assert.throws(() => findFreeRun([4294967296], 32, 1), Error, "word above the maximum");
assert.throws(() => findFreeRun([1.5], 32, 1), Error, "fractional word");
assert.throws(() => findFreeRun([0], 0, 1), Error, "capacity of zero");
assert.throws(() => findFreeRun([0, 0], 32, 1), Error, "word count disagrees with capacity");
assert.throws(() => findFreeRun([1024], 10, 1), Error, "stray bit beyond the capacity");
assert.throws(() => findFreeRun([0], 32, 0), Error, "run length of zero");
assert.throws(() => bitAt([0], 32), Error, "index outside the words");
assert.throws(() => occupyRun([1], 0, 1), Error, "run touching an occupied block");
assert.throws(() => occupyRun([0], 30, 3), Error, "run leaving the words");
console.log("ok");
